In [13]:
import json
import matplotlib.pyplot as plt
from glob import glob
from collections import Counter

In [4]:
json_files = glob("results/*.json")

In [6]:
mining_results = []
for p in json_files:
    with open(p) as f:
        mining_results.append(json.load(f))

In [14]:
keywords = ["snakemake", "nextflow", "cromwell", "WDL", "synthetic"]
summary = {
    'abstract': {
        kw : Counter() for kw in keywords
    },
    'title': {
        kw : Counter() for kw in keywords
    }
}

In [15]:
for r in mining_results:
    for part in ['abstract', 'title']:
        for kw in keywords:
            summary[part][kw] += r[part][kw]

In [16]:
summary

{'abstract': {'snakemake': Counter({'2012': 1,
           '2018': 3,
           '2016': 1,
           '2017': 4}),
  'nextflow': Counter({'2018': 2, '2017': 1}),
  'cromwell': Counter({'2003': 1,
           '2008': 4,
           '2012': 2,
           '2015': 1,
           '2011': 3,
           '2001': 1,
           '1983': 2,
           '1977': 34,
           '1979': 6,
           '1985': 1,
           '1991': 2,
           '1986': 3,
           '1965': 2,
           '1970': 4,
           '1941': 18,
           '1910': 9,
           '2007': 5,
           '1987': 2,
           '1980': 1,
           '2017': 2,
           '1984': 1,
           '2018': 1,
           '2010': 1,
           '2014': 2,
           '1978': 1,
           '2002': 1,
           '1994': 1}),
  'WDL': Counter(),
  'synthetic': Counter({'2008': 10425,
           '2009': 10643,
           '1982': 3622,
           '2007': 9796,
           '1983': 4660,
           '1984': 4669,
           '1985': 4767,
           '1986': 5526,
           '1987': 5893,
           '1968': 9685,
           '1990': 6164,
           '2004': 8528,
           '2005': 8847,
           '1997': 5900,
           '1981': 4019,
           '1976': 3394,
           '2002': 8233,
           '2003': 8114,
           '1975': 3288,
           '2001': 7401,
           '2000': 7479,
           '1967': 10759,
           '1999': 6750,
           '1962': 2030,
           '1961': 2344,
           '1960': 2379,
           '1998': 6210,
           '2014': 15776,
           '1980': 4322,
           '2013': 14126,
           '1979': 3358,
           '1994': 6500,
           '1995': 6264,
           '2015': 16745,
           '1978': 3268,
           '2011': 12387,
           '1993': 6342,
           '1977': 2924,
           '2012': 13785,
           '2016': 17664,
           '2017': 17892,
           '2018': 19967,
           '1972': 4309,
           '2006': 9196,
           '2010': 11244,
           '1996': 6223,
           '1991': 6498,
           '1971': 3996,
           '1970': 2691,
           '1973': 4107,
           '1974': 3426,
           '1989': 5907,
           '1959': 1190,
           '1969': 4968,
           '1963': 2827,
           '1913': 9,
           '1937': 16,
           '1946': 37,
           '1880': 21,
           '1966': 2439,
           '1886': 29,
           '1940': 27,
           '1930': 52,
           '1992': 6395,
           '1915': 11,
           '1916': 18,
           '1935': 34,
           '1988': 5984,
           '1895': 16,
           '1899': 34,
           '1893': 30,
           '1958': 56,
           '1943': 67,
           '1947': 14,
           '1924': 48,
           '1904': 16,
           '1954': 10,
           '1903': 27,
           '1898': 20,
           '1932': 18,
           '1965': 2746,
           '1964': 3924,
           '1922': 12,
           '1914': 37,
           '1939': 83,
           '1918': 1,
           '1928': 1,
           '1929': 4,
           '1931': 26,
           '1948': 62,
           '1921': 4,
           '1920': 18,
           '1919': 1,
           '1897': 10,
           '1890': 14,
           '2019': 261,
           '1952': 4,
           '1956': 157,
           '1957': 1992,
           '1936': 59,
           '1938': 2,
           '1941': 21,
           '1942': 5,
           '1944': 31,
           '1945': 33,
           '1923': 1,
           '1925': 1,
           '1926': 2,
           '1951': 1,
           '1892': 21,
           '1887': 17,
           '1953': 9,
           '1950': 9,
           '1949': 83,
           '1955': 6,
           '1891': 26,
           '1910': 12,
           '1884': 23,
           '1901': 19,
           '1912': 8,
           '1883': 35,
           '1865': 9,
           '1876': 10,
           '1874': 10,
           '1869': 21,
           '1879': 21,
           '1882': 14,
           '1888': 9,
           '1889': 20,
           '1885': 10,
           '1902': 10,
           '1900': 11,
           '1894': 37,
           '1907': 10,
           '1906': 7,
           '1905': 8})},
 'title': {'snakemake': Counter({'2012': 1, '2018': 4}),
  'nextflow': Counter({'2017': 2, '2018': 1}),
  'cromwell': Counter({'2011': 2,
           '1975': 1,
           '1978': 1,
           '1988': 1,
           '1991': 1,
           '2005': 1,
           '1986': 1,
           '2007': 1,
           '1982': 4,
           '2017': 1,
           '1983': 1,
           '1930': 1,
           '1980': 1,
           '1931': 1,
           '2012': 1,
           '1971': 1,
           '1984': 1}),
  'WDL': Counter(),
  'synthetic': Counter({'2008': 1653,
           '2009': 1765,
           '1982': 668,
           '2007': 1606,
           '1983': 777,
           '1984': 803,
           '1985': 781,
           '1986': 913,
           '1990': 993,
           '2005': 1467,
           '1997': 876,
           '2003': 1300,
           '2004': 1344,
           '1981': 656,
           '2001': 1175,
           '2000': 1089,
           '1999': 959,
           '1961': 315,
           '1962': 333,
           '1960': 288,
           '1998': 916,
           '1980': 636,
           '1994': 1037,
           '1995': 974,
           '2013': 2340,
           '2014': 2561,
           '1979': 645,
           '2015': 2697,
           '1993': 995,
           '2016': 2871,
           '2017': 3025,
           '2002': 1239,
           '1972': 655,
           '2012': 2261,
           '2011': 2026,
           '1967': 492,
           '2006': 1429,
           '1996': 983,
           '1969': 503,
           '1971': 573,
           '1970': 517,
           '1973': 668,
           '1974': 708,
           '1989': 1003,
           '1975': 657,
           '1987': 921,
           '1930': 3,
           '1946': 40,
           '1963': 364,
           '1935': 11,
           '1959': 252,
           '1977': 659,
           '1892': 1,
           '1966': 416,
           '1939': 12,
           '1968': 528,
           '1927': 4,
           '1964': 418,
           '1926': 6,
           '1988': 975,
           '1978': 652,
           '1976': 711,
           '2010': 1795,
           '1929': 6,
           '1991': 1072,
           '1942': 12,
           '1947': 55,
           '2018': 3281,
           '1948': 125,
           '1992': 1027,
           '1950': 194,
           '1954': 131,
           '1914': 2,
           '1965': 477,
           '2019': 41,
           '1958': 208,
           '1952': 224,
           '1951': 148,
           '1949': 85,
           '1953': 143,
           '1955': 173,
           '1956': 172,
           '1957': 189,
           '1944': 7,
           '1938': 12,
           '1912': 2,
           '1922': 1,
           '1936': 3,
           '1945': 4,
           '1918': 1,
           '1923': 1,
           '1928': 2,
           '1931': 5,
           '1934': 4,
           '1937': 12,
           '1940': 16,
           '1943': 5,
           '1941': 7,
           '1898': 1,
           '1911': 1,
           '1894': 2,
           '1913': 1,
           '1861': 1,
           '1828': 1,
           '1925': 2,
           '1881': 1,
           '1919': 2,
           '1924': 2,
           '1932': 3,
           '1933': 4,
           '1859': 1,
           '1905': 1,
           '1917': 1})}}